accounts/urls.py
# Django imports
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

# Views.py imports
from . import views


app_name = 'accounts'

urlpatterns = [

    # Login
    path(
        'login/', auth_views.LoginView.as_view(
            redirect_authenticated_user=True,
            template_name='registration/login.html'
        ), name='login'
    ),
    path(
        'logout/', auth_views.LogoutView.as_view(
            next_page=None,
            template_name='registration/logout.html'
        ), name='logout'
    ),

    # Password change
    path(
        'password-change/', auth_views.PasswordChangeView.as_view(
            success_url='done/',
            template_name='registration/password_change.html'
        ), name='password-change'
    ),
    path(
        'password-change/done/', auth_views.PasswordChangeDoneView.as_view(
            template_name='registration/password_change_done.html'
        ), name='password-change-done'
    ),

    # Password reset
    path(
        'password-reset/', auth_views.PasswordResetView.as_view(
            email_template_name='mail/password_reset_email.html',
            html_email_template_name='mail/password_reset_email.html',
            template_name='registration/password_reset.html',
            success_url='done/'
        ), name='password-reset'
    ),
    path(
        'password-reset/done/', auth_views.PasswordResetDoneView.as_view(
            template_name='registration/password_reset_done.html'
        ), name='password-reset-done'
    ),
    path(
        'reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password-reset-complete')
        ), name='password-reset-confirm'
    ),
    path(
        'reset/complete/', auth_views.PasswordResetCompleteView.as_view(
            template_name='registration/password_reset_complete.html'
        ), name='password-reset-complete'
    ),

    # Create
    path('create/', views.CreateAccountView.as_view(), name='create'),
    path('create/done/', views.DoneCreateAccountView.as_view(), name='create-done'),

    # Settings
    path('settings/', views.SettingsView.as_view(), name='settings'),

    # Profile
    path('profile/<user>/', views.ProfileView.as_view(), name='profile'),
    path(
        'profile/<user>/update/', views.UpdateProfileView.as_view(), name='update'
    ),
]

contacts/urls.py
# Django imports
from django.urls import path

# Views import
from . import views


app_name = 'contacts'

urlpatterns = [
    # Home
    path('', views.Index.as_view(), name='home'),

    # Add
    path('add/', views.AddContactView.as_view(), name='add'),

    # Favorite
    path('favorite/list/', views.FavoriteListView.as_view(), name='favorites'),
    path(
        'favorite/<pk>/add/', views.AddFavoriteView.as_view(),
        name='add-favorite'
    ),

    # File
    path('filed/list/', views.FiledListView.as_view(), name='filed'),
    path('filed/<pk>/add/', views.AddFiledView.as_view(), name='add-filed'),

    # Update
    path('update/<pk>/', views.UpdateContactView.as_view(), name='update'),

    # Delete
    path('delete/<pk>/', views.DeleteContactView.as_view(), name='delete'),
]

contacts_calendar/urls.py
# Django imports
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    # Admin site
    path('admin/', admin.site.urls),

    # Page sites
    path('', include('contacts.urls')),
    path('accounts/', include('accounts.urls')),
]
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
# Python imports
from uuid import uuid4

# Django imports
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager


# Custom create user/superuser funcs
class AccountUserManager(UserManager):
    """
    Class UserManager extended to create users by replacing
    username with email.
    """
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Email is required')

        if User.objects.filter(email=email).exists():
            return ValueError('Email is already registered')

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(
            email=email,
            password=password,
            is_active=True,
            **extra_fields
        )

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self._create_user(
            email=email,
            password=password,
            **extra_fields
        )


# Custom model User
class User(AbstractUser):
    """
    User model with customized fields.
    """
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    user_uuid = models.UUIDField(default=uuid4, editable=False)
    username = models.CharField(
        unique=True,
        max_length=50
    )
    email = models.EmailField(unique=True, max_length=254)

    objects = AccountUserManager()

    def __str__(self):
        return self.email

accounts/forms.py
# Django imports
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

# App imports
from .models import User


# Custom form for user creation
class CustomCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            'email',
            'username',
            'password1',
            'password2',
        )


# Custom form for update or change user data
class CustomChangeForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        model = User
        fields = (
            'username',
        )

accounts/views.py
# Env vars load
import os

from dotenv import load_dotenv
load_dotenv()

# Django imports
from django.shortcuts import redirect
from django.views.generic.edit import UpdateView, CreateView
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.core.mail import send_mail
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template.loader import render_to_string
from django.utils.html import strip_tags

# App imports
from .models import User
from .forms import CustomCreationForm, CustomChangeForm


def _welcome_mail(email):
    """
    Send a welcome email to new users.
    """
    html_message = render_to_string('mail/welcome_mail.html')
    html_plain_text = strip_tags(html_message)

    send_mail(
        'Welcome to Contacts Calendar!',
        html_plain_text,
        os.getenv('EMAIL_SENDER'),
        [email],
        fail_silently=False,
        html_message=html_message
    )


class SettingsView(TemplateView):
    """
    Settings of account; profile, change password and email.
    """
    template_name = 'accounts/settings.html'


class ProfileView(LoginRequiredMixin, ListView):
    """
    Display user data in view mode.
    """
    model = User
    template_name = 'accounts/profile.html'
    context_object_name = 'user_data'

    def get_queryset(self):
        user = User.objects.filter(email=self.request.user.email)

        return user


class UpdateProfileView(LoginRequiredMixin, UpdateView):
    """
    Allows modifying user by omitting email and password.
    """
    login_url = '/accounts/login/'
    model = User
    form_class = CustomChangeForm
    template_name = 'accounts/update_account.html'
    success_url = '/accounts/settings/'

    def get_object(self, queryset=None):
        return self.request.user


class CreateAccountView(CreateView):
    """
    Create an account and send a welcome mail.
    """
    model = User
    form_class = CustomCreationForm
    template_name = 'accounts/create_account.html'
    success_url = '/accounts/login'

    def dispatch(self, request, *args, **kwargs):
        """
        If a user is registered redirect to principal page,
        if not, proceed to register.
        """
        if request.user.is_authenticated:
            return redirect('accounts:login')

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        email = form.cleaned_data['email']

        _welcome_mail(email)

        return super().form_valid(form)


class DoneCreateAccountView(TemplateView):
    """
    Load done create account view and redirect to
    principal page, if is not the case it also redirects
    to principal page.
    """
    template_name = 'accounts/create_account_done.html'

    def dispatch(self, request, *args, **kwargs):
        # If not user auth redirect to principal page
        if not request.user.is_authenticated:
            return redirect('contact_list:index')

        return super().dispatch(request, *args, **kwargs)

accounts/templates/accounts/account_update_form.html
{% extends 'base/base.html' %}

{% block title %} Update account form {% endblock title %}

{% block text %}
    <p>Update account</p>

    <form action="" method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <input type="submit" value="Update">
    </form>
{% endblock text %}

accounts/templates/accounts/create_account.html
{% extends 'base/accounts_base.html' %}

{% block title %}Create account{% endblock %}

{% block body_title %}Create account{% endblock %}

{% block body_main %}
<div class="grid justify-center m-3">
  <form method="post">
    {% csrf_token %}

    <div class="mb-1" role="alert">
      <span class="text-sm text-red-600 italic">
        {{ form.non_field_errors }}
      </span>
    </div>

    <div class="bg-gray-100 grid sm:grid-cols-1 md:grid-cols-2 gap-4 border border-gray-500 rounded-lg m-2 p-3">
      <div class="font-serif text-left text-xl md:row-span-1 md:col-span-2 border-b border-gray-500">
        <p>Account Information</p>
      </div>

      <div class="text-left">
        <label class="block text-lg font-serif" for="id_email">
          Email
        </label>
        <input
          class="appearance-none bg-gray-200 text-gray-700 w-full py-1 px-2 border border-blue-400 rounded leading-tight focus:outline-none focus:shadow-outline"
          type="email" name="email" id="id_email">
        <div class="mt-1" role="alert">
          <span class="text-sm text-red-600 italic">
            {{ form.email.errors }}
          </span>
        </div>
      </div>

      <div class="text-left">
        <label class="block text-lg font-serif" for="id_username">
          Username
        </label>
        <input
          class="appearance-none bg-gray-200 text-gray-700 w-full py-1 px-2 border border-blue-400 rounded leading-tight focus:outline-none focus:shadow-outline"
          type="text" name="username" id="id_username">
        <div class="mt-1" role="alert">
          <span class="text-sm text-red-600 italic">
            {{ form.username.errors }}
          </span>
        </div>
      </div>

      <div class="text-left">
        <label class="block text-lg font-serif" for="id_password1">
          Password
        </label>
        <input
          class="appearance-none bg-gray-200 text-gray-700 w-full py-1 px-2 border border-blue-400 rounded leading-tight focus:outline-none focus:shadow-outline"
          type="password" name="password1" id="id_password1">
        <div class="mt-1" role="alert">
          <span class="text-sm text-red-600 italic">
            {{ form.password1.errors }}
          </span>
        </div>
      </div>

      <div class="text-left">
        <label class="block text-lg font-serif" for="id_password2">
          Confirm Password
        </label>
        <input
          class="appearance-none bg-gray-200 text-gray-700 w-full py-1 px-2 border border-blue-400 rounded leading-tight focus:outline-none focus:shadow-outline"
          type="password" name="password2" id="id_password2">
        <div class="mt-1" role="alert">
          <span class="text-sm text-red-600 italic">
            {{ form.password2.errors }}
          </span>
        </div>
      </div>
    </div>

    <div class="flex justify-between m-2">
      <a class="block text-purple-500 font-mono bg-transparent hover:underline rounded mt-3 p-2"
        href="{% url 'accounts:login' %}">
        Login
      </a>
      <button
        class="block font-mono bg-green-300 border-green-300 hover:border-transparent hover:bg-green-500 rounded mt-3 p-2"
        type="submit">
        Create
      </button>
    </div>
  </form>
</div>
{% endblock body_main %}

accounts/templates/accounts/create_account_done.html
{% extends 'base/accounts_base.html' %}

{% block title %} Create account done {% endblock %}

{% block body_title %}Thanks!{% endblock %}

{% block body_main %}
<div class="grid justify-center m-2 p-3">
  <div class="bg-green-200 border border-gray-500 rounded-lg mb-3 p-3">
    <p class="text-lg">
      Your account is successfuly created, thanks!
    </p>
  </div>

  <div class="text-center font-serif">
    <p class="">
      <a class="text-blue-500 hover:underline" href="{% url 'contacts:home' %}">
        [Redirect to principal page]
      </a>
    </p>
  </div>
</div>
{% endblock body_main %}

accounts/templates/accounts/profile.html
{% extends 'base/accounts_base.html' %}

{% block title %} Profile {% endblock %}

{% block body_title %}Profile{% endblock %}

{% block body_main %}
<div class="grid grid-rows-1 gap-4 justify-center m-2 pb-8">
  <div
    class="bg-gray-100 grid sm:grid-cols-1 md:grid-cols-2 gap-4 rounded-lg border border-solid border-gray-600 m-2 p-3">
    <div class="w-full md:row-span-1 md:col-span-2 text-left text-xl font-serif border-b border-gray-500">
      <p>Account</p>
    </div>
    <div class="text-left p-2">
      <label class="block text-lg font-serif" for="">
        Username
      </label>
      <p class="font-light italic">
        {{ user.username }}
      </p>
    </div>
    <div class="text-left p-2">
      <label class="block text-lg font-serif" for="">
        Email
      </label>
      <p class="font-light italic">
        {{ user.email }}
      </p>
    </div>
  </div>

  <div class="flex justify-between m-2">
    <a class="block font-mono bg-transparent border-dashed border-2 border-blue-400 hover:border-transparent hover:bg-blue-400 hover:text-white rounded p-2"
      href="{% url 'accounts:settings' %}">
      Back
    </a>
    <a class="block font-mono bg-teal-200 border-double border-2 border-teal-400 hover:bg-teal-400 hover:text-white rounded p-2"
      href="{% url 'accounts:update' request.user.username %}">
      Update
    </a>
  </div>
</div>
{% endblock body_main %}

accounts/templates/accounts/settings.html
{% extends 'base/contact_list_base.html' %}

{% block title %}Settings{% endblock %}

{% block body_main %}
<div class="grid gap-4 justify-center">
  <div class="grid sm:grid-cols-1 md:grid-cols-2 gap-4 rounded-lg border border-gray-600 bg-gray-100 m-4 p-3">
    <div class="md:row-span-1 md:col-span-2 text-left text-xl font-serif border-b border-gray-500">
      <p>App settings</p>
    </div>
    <div class="text-left m-2 p-1">
      <label class="block text-lg font-serif" for="">
        Personal information
      </label>
      <a class="text-purple-500 font-mono hover:underline rounded"
        href="{% url 'accounts:profile' request.user.username %}">
        Profile
      </a>
    </div>
    <div class="text-left m-2 p-1">
      <label class="block text-lg font-serif" for="">
        Dark theme
      </label>
      <a class="text-purple-500 font-mono hover:underline rounded" href="#">
        Future
      </a>
    </div>
  </div>

  <div class="grid sm:grid-cols-1 md:grid-cols-2 gap-4 rounded-lg border border-gray-600 bg-gray-100 m-4 p-3">
    <div class="md:row-span-1 md:col-span-2 text-left text-xl font-serif border-b border-gray-500">
      <p>Account</p>
    </div>
    <div class="text-left m-2 p-1">
      <label class="block text-lg font-serif" for="">
        Password
      </label>
      <a class="text-purple-500 font-mono hover:underline rounded" href="{% url 'accounts:password-change' %}">
        Change password
      </a>
    </div>
  </div>

  <div class="text-center m-4">
    <a class="block font-mono text-indigo-500 bg-transparent border-dashed border-2 border-indigo-500 hover:bg-indigo-500 hover:text-white rounded p-2"
      href="{% url 'contacts:home' %}">
      Index
    </a>
  </div>
</div>
{% endblock body_main %}

accounts/templates/accounts/success_create_account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="refresh" content="3; url=http://127.0.0.1:8000">
    <title>Document</title>
</head>
<body>
    <p>
        Thanks, your account is successfuly created.
        Redirect to principal page...
    </p>
</body>
</html>

accounts/templates/accounts/update_account.html
{% extends 'base/accounts_base.html' %}

{% block title %}Update account{% endblock %}

{% block body_title %}Update account{% endblock %}

{% block body_main %}
<div class="grid justify-center m-3">
  <form method="post">
    {% csrf_token %}

    <div class="bg-gray-100 mb-1" role="alert">
      <span class="text-sm text-red-600 italic">
        {{ form.non_field_errors }}
      </span>
    </div>

    <div class="bg-gray-100 grid sm:grid-cols-1 md:grid-cols-3 gap-4 border border-gray-500 rounded-lg m-2 p-3">
      <div class="md:row-span-1 md:col-span-3 text-left text-xl font-serif border-b border-gray-500">
        <p>Account</p>
      </div>
      <div class="text-left">
        <label class="block text-lg font-serif" for="">
          Username
        </label>
        <input
          class="font-sans appearance-none bg-gray-200 text-gray-700 w-full py-1 px-2 border border-blue-400 rounded leading-tight focus:outline-none focus:shadow-outline"
          type="text" name="username" id="" value="{{ user.username }}">
        <div class="mt-1" role="alert">
          <span class="text-sm text-red-600 italic">
            {{ form.username.errors }}
          </span>
        </div>
      </div>
    </div>

    <div class="m-2">
      <div class="flex justify-between">
        <a class="block font-mono bg-blue-300 border-blue-300 hover:border-transparent hover:bg-blue-500 rounded mt-3 p-2"
          href="{% url 'accounts:profile' request.user.username %}">
          Cancel
        </a>
        <button
          class="block font-mono bg-green-300 border-green-300 hover:border-transparent hover:bg-green-500 rounded mt-3 p-2"
          type="submit">
          Update
        </button>
      </div>
    </div>
  </form>
</div>
{% endblock body_main %}