accounts/urls.py
# Django imports
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

# Views.py imports
from . import views


app_name = 'accounts'

urlpatterns = [

    # Login
    path(
        'login/', auth_views.LoginView.as_view(
            redirect_authenticated_user=True,
            template_name='registration/login.html'
        ), name='login'
    ),
    path(
        'logout/', auth_views.LogoutView.as_view(
            next_page=None,
            template_name='registration/logout.html'
        ), name='logout'
    ),

    # Password change
    path(
        'password-change/', auth_views.PasswordChangeView.as_view(
            success_url='done/',
            template_name='registration/password_change.html'
        ), name='password-change'
    ),
    path(
        'password-change/done/', auth_views.PasswordChangeDoneView.as_view(
            template_name='registration/password_change_done.html'
        ), name='password-change-done'
    ),

    # Password reset
    path(
        'password-reset/', auth_views.PasswordResetView.as_view(
            email_template_name='mail/password_reset_email.html',
            html_email_template_name='mail/password_reset_email.html',
            template_name='registration/password_reset.html',
            success_url='done/'
        ), name='password-reset'
    ),
    path(
        'password-reset/done/', auth_views.PasswordResetDoneView.as_view(
            template_name='registration/password_reset_done.html'
        ), name='password-reset-done'
    ),
    path(
        'reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password-reset-complete')
        ), name='password-reset-confirm'
    ),
    path(
        'reset/complete/', auth_views.PasswordResetCompleteView.as_view(
            template_name='registration/password_reset_complete.html'
        ), name='password-reset-complete'
    ),

    # Create
    path('create/', views.CreateAccountView.as_view(), name='create'),
    path('create/done/', views.DoneCreateAccountView.as_view(), name='create-done'),

    # Settings
    path('settings/', views.SettingsView.as_view(), name='settings'),

    # Profile
    path('profile/<user>/', views.ProfileView.as_view(), name='profile'),
    path(
        'profile/<user>/update/', views.UpdateProfileView.as_view(), name='update'
    ),
]

contacts/urls.py
# Django imports
from django.urls import path

# Views import
from . import views


app_name = 'contacts'

urlpatterns = [
    # Home
    path('', views.Index.as_view(), name='home'),

    # Add
    path('add/', views.AddContactView.as_view(), name='add'),

    # Favorite
    path('favorite/list/', views.FavoriteListView.as_view(), name='favorites'),
    path(
        'favorite/<pk>/add/', views.AddFavoriteView.as_view(),
        name='add-favorite'
    ),

    # File
    path('filed/list/', views.FiledListView.as_view(), name='filed'),
    path('filed/<pk>/add/', views.AddFiledView.as_view(), name='add-filed'),

    # Update
    path('update/<pk>/', views.UpdateContactView.as_view(), name='update'),

    # Delete
    path('delete/<pk>/', views.DeleteContactView.as_view(), name='delete'),
]

contacts_calendar/urls.py
# Django imports
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    # Admin site
    path('admin/', admin.site.urls),

    # Page sites
    path('', include('contacts.urls')),
    path('accounts/', include('accounts.urls')),
]
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contacts/models.py
# Django imports
from django.db import models

# Library imports
from phone_field import PhoneField

# Python imports
from datetime import date, datetime

# App imports
from accounts.models import User


# Model for contacts data
class ContactField(models.Model):
    """
    Model for contacts, FK to User model.
    """
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    full_name = models.CharField(max_length=50, default='Cosme Fulanito')
    phone_number = PhoneField(default='00000000')
    contact_email = models.EmailField(
        max_length=254,
        default='empty@cc.com'
    )
    date_of_birth = models.DateField(
        auto_now=False,
        auto_now_add=False,
        default=date.today
    )
    favorite = models.BooleanField(default=False)
    filed = models.BooleanField(default=False)

    def __str__(self):
        today = datetime.now()
        date_id = str(today.year) + str(today.month) + str(today.day)
        time_id = str(today.hour) + str(today.minute) + str(today.second)
        str_id = str(self.user_id) + str(self.id) + date_id + time_id

        return str_id

contacts/forms.py
# Django imports
from django import forms

# App imports
from .models import ContactField


class AddContactForm(forms.ModelForm):

    class Meta:
        model = ContactField
        fields = [
            'user',
            'full_name',
            'contact_email',
            'date_of_birth',
            'phone_number',
        ]

contacts/views.py
# Django imports
from django.views.generic import CreateView, DeleteView, UpdateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin

# App imports
from contacts.models import ContactField
from contacts.forms import AddContactForm


class Index(ListView):
    """
    Show all contacts of the current user.
    """
    model = ContactField
    context_object_name = 'all_contacts'
    template_name = 'contacts/index.html'
    paginate_by = 9

    def get_queryset(self):
        all_contacts = ContactField.objects.filter(
            user=self.request.user.id
        ).order_by('id')

        return all_contacts


class AddContactView(LoginRequiredMixin, CreateView):
    """
    Add a new contact.
    """
    model = ContactField
    form_class = AddContactForm
    template_name = 'contacts/add_contact.html'
    success_url = '/'


class UpdateContactView(LoginRequiredMixin, UpdateView):
    """
    Update fields of the selected contact.
    """
    model = ContactField
    fields = [
        'full_name',
        'contact_email',
        'phone_number',
        'date_of_birth'
    ]
    template_name = 'contacts/update_contact.html'
    success_url = '/'


class AddFavoriteView(LoginRequiredMixin, UpdateView):
    """
    Add a contact to the user's favorite list.
    """
    model = ContactField
    fields = [
        'favorite'
    ]
    template_name = 'contacts/add_favorite.html'
    success_url = '/'


class FavoriteListView(LoginRequiredMixin, ListView):
    """
    Displays the list of favorite contacts.
    """
    model = ContactField
    context_object_name = 'favorite_contacts'
    template_name = 'contacts/favorite_list.html'
    # paginate_by = 9

    def get_queryset(self):
        favorite_contacts = ContactField.objects.filter(
            user=self.request.user.id,
            favorite=True
        )

        return favorite_contacts


class AddFiledView(LoginRequiredMixin, UpdateView):
    """
    Add a contact to the user's filed list.
    """
    model = ContactField
    fields = [
        'filed'
    ]
    template_name = 'contacts/add_filed.html'
    success_url = '/'


class FiledListView(LoginRequiredMixin, ListView):
    """
    Displays the list of filed contacts.
    """
    model = ContactField
    context_object_name = 'filed_contacts'
    template_name = 'contacts/filed_list.html'
    # paginate_by = 9

    def get_queryset(self):
        filed_contacts = ContactField.objects.filter(
            user=self.request.user.id,
            filed=True
        )
        return filed_contacts


class DeleteContactView(LoginRequiredMixin, DeleteView):
    """
    Remove a contact from the user's contact list.
    """
    model = ContactField
    template_name = 'contacts/delete_contact.html'
    success_url = '/'

contacts/templates/contacts/add_contact.html
{% extends 'base/contact_list_base.html' %}

{% block title %}Add - Contacts calendar{% endblock %}

{% block body_main %}
<div class="grid justify-center m-2 p-3">
  <form method="post">
    {% csrf_token %}

    <input type="hidden" value="{{ request.user.id }}" name="{{ form.user.html_name }}">

    <div class="mb-1" role="alert">
      <span class="text-sm text-red-600 italic">
        {{ form.non_field_errors }}
      </span>
    </div>

    <div class="bg-gray-100 grid sm:grid-cols-1 md:grid-cols-2 gap-4 rounded-lg border border-gray-500 m-2 p-3">
      <div class="md:row-span-1 md:col-span-2 border-b">
        <div class="text-left">
          <p class="text-xl font-serif">
            Add contact
          </p>
        </div>
      </div>

      <div class="m-1">
        <label class="block text-lg font-serif mb-2" for="{{ form.full_name.id_for_label }}">
          Full name
        </label>
        <input
          class="appearance-none bg-gray-200 text-gray-700 w-full py-1 px-2 border border-blue-400 rounded leading-tight focus:outline-none focus:shadow-outline"
          type="text" name="{{ form.full_name.html_name }}" id="{{ form.full_name.auto_id }}">
        <div class="mt-1" role="alert">
          <span class="text-sm text-red-600 italic">
            {{ form.full_name.errors }}
          </span>
        </div>
      </div>

      <div class="m-1">
        <label class="block font-serif mb-2" for="{{ form.contact_email.id_for_label }}">
          Email
        </label>
        <input
          class="appearance-none bg-gray-200 text-gray-700 w-full py-1 px-2 border border-blue-400 rounded leading-tight focus:outline-none focus:shadow-outline"
          type="email" name="{{ form.contact_email.html_name }}" id="{{ form.contact_email.auto_id }}">
        <div class="mt-1" role="alert">
          <span class="text-sm text-red-600 italic">
            {{ form.contact_email.errors }}
          </span>
        </div>
      </div>

      <div class="m-1">
        <label class="block font-serif mb-2" for="{{ form.phone_number.id_for_label }}">
          Phone
        </label>
        <input
          class="appearance-none bg-gray-200 text-gray-700 w-full py-1 px-2 border border-blue-400 rounded leading-tight focus:outline-none focus:shadow-outline"
          type="tel" name="phone_number_0" id="id_phone_number_0">
        <div class="mt-1" role="alert">
          <span class="text-sm text-red-600 italic">
            {{ form.phone_number.errors }}
          </span>
        </div>
      </div>

      <div class="m-1">
        <label class="block font-serif mb-2" for="{{ form.date_of_birth.id_for_label }}">
          Birth date
        </label>
        <input
          class="font-sans text-sm appearance-none bg-gray-200 text-gray-700 w-full py-1 px-2 border border-blue-400 rounded leading-tight focus:outline-none focus:shadow-outline"
          type="date" name="{{ form.date_of_birth.html_name }}" id="{{ form.date_of_birth.auto_id }}">
        <div class="mt-1" role="alert">
          <span class="text-sm text-red-600 italic">
            {{ form.date_of_birth.errors }}
          </span>
        </div>
      </div>
    </div>

    <div class="flex justify-between m-2 pt-2">
      <div class="">
        <a class="block text-red-500 bg-transparent font-mono hover:underline p-2" href="{% url 'contacts:home' %}">
          Cancel
        </a>
      </div>
      <div class="">
        <button class="font-mono bg-teal-300 border-teal-300 hover:border-transparent hover:bg-teal-500 rounded p-2"
          type="submit">
          Create
        </button>
      </div>
    </div>
  </form>
</div>
{% endblock body_main %}

contacts/templates/contacts/add_favorite.html
{% extends 'base/contact_list_base.html' %}

{% block title %}Contacts calendar{% endblock %}

{% block body_main %}
{% if object.favorite %}
<div class="grid justify-center m-2 p-3">
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="favorite" value="False">

    <div class="bg-gray-100 border border-gray-500 rounded-lg m-2 p-3">
      <div class="m-2">
        <p class="text-lg font-semibold">
          Confirm to remove contact from the favorites:
        </p>
      </div>

      <div class="text-center pt-3">
        <button
          class="font-semibold text-white w-full bg-green-500 hover:bg-green-600 border border-green-500 rounded p-2"
          type="submit">
          Remove
        </button>
      </div>

      <div class="text-center pt-2">
        <a class="block bg-transparent hover:bg-red-500 text-red-500 font-mono hover:text-white p-1 border-dashed border-2 border-red-300 hover:border-red-500 rounded"
          href="{% url 'contacts:home' %}">
          Cancel
        </a>
      </div>
    </div>
  </form>
</div>
{% else %}
<div class="grid justify-center m-2 p-3">
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="favorite" value="True">

    <div class="bg-gray-100 border border-gray-500 rounded-lg m-2 p-3">
      <div class="m-2">
        <p class="text-lg font-semibold">
          Confirm to add contact to the favorites:
        </p>
      </div>

      <div class="text-center pt-3">
        <button
          class="font-semibold text-white w-full bg-green-500 hover:bg-green-600 border border-green-500 rounded p-2"
          type="submit">
          Add
        </button>
      </div>

      <div class="text-center pt-2">
        <a class="block bg-transparent hover:bg-red-500 text-red-500 font-mono hover:text-white p-1 border-dashed border-2 border-red-300 hover:border-red-500 rounded"
          href="{% url 'contacts:home' %}">
          Cancel
        </a>
      </div>
    </div>
  </form>
</div>
{% endif %}
{% endblock body_main %}

contacts/templates/contacts/add_filed.html
{% extends 'base/contact_list_base.html' %}

{% block title %}Contacts calendar{% endblock %}

{% block body_main %}
{% if object.filed %}
<div class="grid justify-center gap-4 m-2 p-3">
  <form class="" method="post">
    {% csrf_token %}
    <input type="hidden" name="filed" value="False">

    <div class="bg-gray-100 border border-gray-500 rounded-lg m-2 p-3">
      <div class="m-2">
        <p class="text-lg font-semibold">
          Confirm to remove contact from the filed list:
        </p>
      </div>

      <div class="text-center pt-3">
        <button
          class="font-semibold text-white w-full bg-green-500 hover:bg-green-600 border border-green-500 rounded p-2"
          type="submit">
          Remove
        </button>
      </div>

      <div class="text-center pt-2">
        <a class="block bg-transparent hover:bg-red-500 text-red-500 font-mono hover:text-white p-1 border-dashed border-2 border-red-300 hover:border-red-500 rounded"
          href="{% url 'contacts:home' %}">
          Cancel
        </a>
      </div>
    </div>
  </form>
</div>
{% else %}
<div class="grid justify-center gap-4 m-2 p-3">
  <form class="" method="post">
    {% csrf_token %}
    <input type="hidden" name="filed" value="True">

    <div class="bg-gray-100 border border-gray-500 rounded-lg m-2 p-3">
      <div class="m-2">
        <p class="text-lg font-semibold">
          Confirm to add contact to the filed list:
        </p>
      </div>

      <div class="text-center pt-3">
        <button
          class="font-semibold text-white w-full bg-green-500 hover:bg-green-600 border border-green-500 rounded p-2"
          type="submit">
          Add
        </button>
      </div>

      <div class="text-center pt-2">
        <a class="block bg-transparent hover:bg-red-500 text-red-500 font-mono hover:text-white p-1 border-dashed border-2 border-red-300 hover:border-red-500 rounded"
          href="{% url 'contacts:home' %}">
          Cancel
        </a>
      </div>
    </div>
  </form>
</div>
{% endif %}
{% endblock body_main %}

contacts/templates/contacts/delete_contact.html
{% extends 'base/contact_list_base.html' %}

{% block title %}Delete - Contacts calendar{% endblock %}

{% block body_main %}
<div class="grid justify-center gap-4 m-2 p-3">
  <form class="" method="post">
    {% csrf_token %}
    <input type="hidden" name="filed" value="False">

    <div class="bg-gray-100 border border-gray-500 rounded-lg m-2 p-3">
      <div class="m-2">
        <p class="text-lg font-semibold">
          Confirm to delete this contact from your account:
        </p>
      </div>

      <div class="text-center pt-3">
        <button
          class="font-semibold text-white w-full bg-green-500 hover:bg-green-600 border border-green-500 rounded p-2"
          type="submit">
          Delete
        </button>
      </div>

      <div class="text-center pt-2">
        <a class="block bg-transparent hover:bg-red-500 text-red-500 font-mono hover:text-white p-1 border-dashed border-2 border-red-300 hover:border-red-500 rounded"
          href="{% url 'contacts:home' %}">
          Cancel
        </a>
      </div>
    </div>
  </form>
</div>
{% endblock body_main %}

contacts/templates/contacts/favorite_list.html
{% extends 'base/contact_list_base.html' %}

{% block title %}Favorites{% endblock %}

{% block body_main %}
{% if favorite_contacts %}
<div class="grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 m-2 p-3">
  {% for contact in favorite_contacts %}

  <div class="grid border border-gray-600 rounded-lg bg-gray-100">
    {% include 'base/contact_top_buttons.html' %}

    {% include 'base/contact_fields.html' %}
  </div>
  {% endfor %}
</div>
{% else %}
<div class="grid justify-center m-2 p-3">
  Anyone contact in the contact list.
</div>
{% endif %}
{% endblock body_main %}

{% block body_footer %}
{% include 'base/contact_pagination.html' %}
{% endblock body_footer %}

contacts/templates/contacts/filed_list.html
{% extends 'base/contact_list_base.html' %}

{% block title %}Filed{% endblock %}

{% block body_main %}
{% if filed_contacts %}
<div class="grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 m-2 p-3">
  {% for contact in filed_contacts %}
  <div class="grid border border-gray-600 rounded-lg bg-gray-100">
    {% include 'base/contact_top_buttons.html' %}

    {% include 'base/contact_fields.html' %}

    {% include 'base/contact_bottom_buttons.html' %}
  </div>
  {% endfor %}
</div>
{% else %}
<div class="grid justify-center m-2 p-3">
  Anyone contact in the filed list.
</div>
{% endif %}
{% endblock body_main %}

{% block body_footer %}
{% include 'base/contact_pagination.html' %}
{% endblock body_footer %}

contacts/templates/contacts/index.html
{% extends 'base/contact_list_base.html' %}

{% block title %}Contacts calendar{% endblock %}

{% block body_main %}
{% if all_contacts %}
<div class="grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 m-2 p-3">
  {% for contact in all_contacts %}
  <div class="grid border border-gray-500 rounded-lg bg-gray-100">
    {% include 'base/contact_top_buttons.html' %}

    {% include 'base/contact_fields.html' %}
  </div>
  {% endfor %}
</div>
{% else %}
<div class="flex justify-center">
  {% if request.user.is_authenticated %}
  Add new contacts in the button add.
  {% else %}
  <div
    class="bg-white flex flex-col justify-self-center justify-items-center border rounded-md border-gray-500 mt-10 m-2 p-3 w-64">
    <div class="text-sm text-center">
      <a class="block text-black hover:text-green-500 rounded lg:mt-0 m-1 p-2" href="{% url 'accounts:login' %}">
        Sign in
      </a>
    </div>

    <div class="text-sm text-center">
      <a class="block text-black border-2 border-green-500 rounded lg:mt-0 m-1 p-2 hover:bg-green-500"
        href="{% url 'accounts:create' %}">
        Sign up
      </a>
    </div>
  </div>
  {% endif %}
</div>
{% endif %}
{% endblock body_main %}

{% block body_footer %}
{% include 'base/contact_pagination.html' %}
{% endblock body_footer %}

contacts/templates/contacts/update_contact.html
{% extends 'base/contact_list_base.html' %}

{% block title %}Update contact{% endblock %}

{% block body_main %}
<div class="grid justify-center m-3">
  <form method="post">
    {% csrf_token %}

    <div class="bg-gray-100 mb-1" role="alert">
      <span class="text-sm text-red-600 italic">
        {{ form.non_field_errors }}
      </span>
    </div>

    <div class="bg-gray-100 grid sm:grid-cols-1 md:grid-cols-3 gap-4 border border-gray-500 rounded-lg m-2 p-3">
      <div class="md:row-span-1 md:col-span-3 text-left text-xl font-serif border-b border-gray-500">
        <p>Update contact</p>
      </div>
      <div class="text-left">
        <label class="block text-lg font-serif" for="">
          Full name
        </label>
        <input
          class="font-sans appearance-none bg-gray-200 text-gray-700 w-full py-1 px-2 border border-blue-400 rounded leading-tight focus:outline-none focus:shadow-outline"
          type="text" name="full_name" id="full_name" value="{{ object.full_name }}">
        <div class="mt-1" role="alert">
          <span class="text-sm text-red-600 italic">
            {{ form.full_name.errors }}
          </span>
        </div>
      </div>
      <div class="text-left">
        <label class="block text-lg font-serif" for="">
          Email
        </label>
        <input
          class="appearance-none bg-gray-200 text-gray-700 w-full py-1 px-2 border border-blue-400 rounded leading-tight focus:outline-none focus:shadow-outline"
          type="email" name="contact_email" id="email" value="{{ object.contact_email }}">
        <div class="mt-1" role="alert">
          <span class="text-sm text-red-600 italic">
            {{ form.email.errors }}
          </span>
        </div>
      </div>
      <div class="text-left">
        <label class="block text-lg font-serif" for="">
          Phone
        </label>
        <input
          class="font-sans appearance-none bg-gray-200 text-gray-700 w-full py-1 px-2 border border-blue-400 rounded leading-tight focus:outline-none focus:shadow-outline"
          type="tel" name="phone_number_0" id="" value="{{ object.phone_number }}">
        <div class="mt-1" role="alert">
          <span class="text-sm text-red-600 italic">
            {{ form.phone_number_0.errors }}
          </span>
        </div>
      </div>
      <div class="text-left">
        <label class="block text-lg font-serif" for="">
          Date of birth
        </label>
        <input
          class="font-sans text-sm appearance-none bg-gray-200 text-gray-700 w-full py-1 px-2 border border-blue-400 rounded leading-tight focus:outline-none focus:shadow-outline"
          type="date" name="date_of_birth" id="" value="{{ object.date_of_birth|date:'Y-m-d' }}">
        <div class="mt-1" role="alert">
          <span class="text-sm text-red-600 italic">
            {{ form.date_of_birth.errors }}
          </span>
        </div>
      </div>
    </div>

    <div class="m-2">
      <div class="flex justify-between">
        <a class="block font-mono bg-blue-300 border-blue-300 hover:border-transparent hover:bg-blue-500 rounded mt-3 p-2"
          href="{% url 'contacts:home' %}">
          Cancel
        </a>
        <button
          class="block font-mono bg-green-300 border-green-300 hover:border-transparent hover:bg-green-500 rounded mt-3 p-2"
          type="submit">
          Update
        </button>
      </div>
    </div>
  </form>
</div>
{% endblock body_main %}