accounts/urls.py
# Django imports
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

# Views.py imports
from . import views


app_name = 'accounts'

urlpatterns = [

    # Login
    path(
        'login/', auth_views.LoginView.as_view(
            redirect_authenticated_user=True,
            template_name='registration/login.html'
        ), name='login'
    ),
    path(
        'logout/', auth_views.LogoutView.as_view(
            next_page=None,
            template_name='registration/logout.html'
        ), name='logout'
    ),

    # Password change
    path(
        'password-change/', auth_views.PasswordChangeView.as_view(
            success_url='done/',
            template_name='registration/password_change.html'
        ), name='password-change'
    ),
    path(
        'password-change/done/', auth_views.PasswordChangeDoneView.as_view(
            template_name='registration/password_change_done.html'
        ), name='password-change-done'
    ),

    # Password reset
    path(
        'password-reset/', auth_views.PasswordResetView.as_view(
            email_template_name='mail/password_reset_email.html',
            html_email_template_name='mail/password_reset_email.html',
            template_name='registration/password_reset.html',
            success_url='done/'
        ), name='password-reset'
    ),
    path(
        'password-reset/done/', auth_views.PasswordResetDoneView.as_view(
            template_name='registration/password_reset_done.html'
        ), name='password-reset-done'
    ),
    path(
        'reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password-reset-complete')
        ), name='password-reset-confirm'
    ),
    path(
        'reset/complete/', auth_views.PasswordResetCompleteView.as_view(
            template_name='registration/password_reset_complete.html'
        ), name='password-reset-complete'
    ),

    # Create
    path('create/', views.CreateAccountView.as_view(), name='create'),
    path('create/done/', views.DoneCreateAccountView.as_view(), name='create-done'),

    # Settings
    path('settings/', views.SettingsView.as_view(), name='settings'),

    # Profile
    path('profile/<user>/', views.ProfileView.as_view(), name='profile'),
    path(
        'profile/<user>/update/', views.UpdateProfileView.as_view(), name='update'
    ),
]

contacts/urls.py
# Django imports
from django.urls import path

# Views import
from . import views


app_name = 'contacts'

urlpatterns = [
    # Home
    path('', views.Index.as_view(), name='home'),

    # Add
    path('add/', views.AddContactView.as_view(), name='add'),

    # Favorite
    path('favorite/list/', views.FavoriteListView.as_view(), name='favorites'),
    path(
        'favorite/<pk>/add/', views.AddFavoriteView.as_view(),
        name='add-favorite'
    ),

    # File
    path('filed/list/', views.FiledListView.as_view(), name='filed'),
    path('filed/<pk>/add/', views.AddFiledView.as_view(), name='add-filed'),

    # Update
    path('update/<pk>/', views.UpdateContactView.as_view(), name='update'),

    # Delete
    path('delete/<pk>/', views.DeleteContactView.as_view(), name='delete'),
]

contacts_calendar/urls.py
# Django imports
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    # Admin site
    path('admin/', admin.site.urls),

    # Page sites
    path('', include('contacts.urls')),
    path('accounts/', include('accounts.urls')),
]
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contacts/models.py
# Django imports
from django.db import models

# Library imports
from phone_field import PhoneField

# Python imports
from datetime import date, datetime

# App imports
from accounts.models import User


# Model for contacts data
class ContactField(models.Model):
    """
    Model for contacts, FK to User model.
    """
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    full_name = models.CharField(max_length=50, default='Cosme Fulanito')
    phone_number = PhoneField(default='00000000')
    contact_email = models.EmailField(
        max_length=254,
        default='empty@cc.com'
    )
    date_of_birth = models.DateField(
        auto_now=False,
        auto_now_add=False,
        default=date.today
    )
    favorite = models.BooleanField(default=False)
    filed = models.BooleanField(default=False)

    def __str__(self):
        today = datetime.now()
        date_id = str(today.year) + str(today.month) + str(today.day)
        time_id = str(today.hour) + str(today.minute) + str(today.second)
        str_id = str(self.user_id) + str(self.id) + date_id + time_id

        return str_id

contacts/forms.py
# Django imports
from django import forms

# App imports
from .models import ContactField


class AddContactForm(forms.ModelForm):

    class Meta:
        model = ContactField
        fields = [
            'user',
            'full_name',
            'contact_email',
            'date_of_birth',
            'phone_number',
        ]

contacts/views.py
# Django imports
from django.views.generic import CreateView, DeleteView, UpdateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin

# App imports
from contacts.models import ContactField
from contacts.forms import AddContactForm


class Index(ListView):
    """
    Show all contacts of the current user.
    """
    model = ContactField
    context_object_name = 'all_contacts'
    template_name = 'contacts/index.html'
    paginate_by = 9

    def get_queryset(self):
        all_contacts = ContactField.objects.filter(
            user=self.request.user.id
        ).order_by('id')

        return all_contacts


class AddContactView(LoginRequiredMixin, CreateView):
    """
    Add a new contact.
    """
    model = ContactField
    form_class = AddContactForm
    template_name = 'contacts/add_contact.html'
    success_url = '/'


class UpdateContactView(LoginRequiredMixin, UpdateView):
    """
    Update fields of the selected contact.
    """
    model = ContactField
    fields = [
        'full_name',
        'contact_email',
        'phone_number',
        'date_of_birth'
    ]
    template_name = 'contacts/update_contact.html'
    success_url = '/'


class AddFavoriteView(LoginRequiredMixin, UpdateView):
    """
    Add a contact to the user's favorite list.
    """
    model = ContactField
    fields = [
        'favorite'
    ]
    template_name = 'contacts/add_favorite.html'
    success_url = '/'


class FavoriteListView(LoginRequiredMixin, ListView):
    """
    Displays the list of favorite contacts.
    """
    model = ContactField
    context_object_name = 'favorite_contacts'
    template_name = 'contacts/favorite_list.html'
    # paginate_by = 9

    def get_queryset(self):
        favorite_contacts = ContactField.objects.filter(
            user=self.request.user.id,
            favorite=True
        )

        return favorite_contacts


class AddFiledView(LoginRequiredMixin, UpdateView):
    """
    Add a contact to the user's filed list.
    """
    model = ContactField
    fields = [
        'filed'
    ]
    template_name = 'contacts/add_filed.html'
    success_url = '/'


class FiledListView(LoginRequiredMixin, ListView):
    """
    Displays the list of filed contacts.
    """
    model = ContactField
    context_object_name = 'filed_contacts'
    template_name = 'contacts/filed_list.html'
    # paginate_by = 9

    def get_queryset(self):
        filed_contacts = ContactField.objects.filter(
            user=self.request.user.id,
            filed=True
        )
        return filed_contacts


class DeleteContactView(LoginRequiredMixin, DeleteView):
    """
    Remove a contact from the user's contact list.
    """
    model = ContactField
    template_name = 'contacts/delete_contact.html'
    success_url = '/'

contacts/templates/base/contact_fields.html
<div class="grid sm:grid-cols-1 lg:grid-cols-2 gap-4 m-3">
  <div class="ml-2">
    <label class="block text-lg font-serif" for="">
      Full name
    </label>
    <p class="font-light italic">
      {{ contact.full_name }}
    </p>
  </div>
  <div class="ml-2">
    <label class="block text-lg font-serif" for="">
      Email
    </label>
    <p class="font-light italic">
      {{ contact.contact_email }}
    </p>
  </div>
  <div class="ml-2">
    <label class="block text-lg font-serif" for="">
      Phone
    </label>
    <p class="font-light italic">
      {{ contact.phone_number }}
    </p>
  </div>
  <div class="ml-2">
    <label class="block text-lg font-serif" for="">
      Date of Birth
    </label>
    <p class="font-light italic">
      {{ contact.date_of_birth }}
    </p>
  </div>
</div>

contacts/templates/base/contact_list_base.html
{% load static %}
{% load tailwind_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shorcut icon" href="https://img.icons8.com/cute-clipart/64/000000/book.png">
  <script src="{% static 'contact_list/js/index.js' %}"></script>
  <script src="{% static 'contact_list/js/optionButtons.js' %}"></script>
  {% tailwind_css %}
  <title>{% block title %}{% endblock %}</title>
</head>

<body class="relative bg-gray-200">
  <nav class="fixed top-0 left-0 right-0 flex justify-between flex-wrap bg-gray-800 p-3">
    <div class="text-gray-200 mr-6 font-semibold text-2xl tracking-tight">
      <a href="{% url 'contacts:home' %}">
        Contacts Calendar
      </a>
    </div>

    <div class="block lg:hidden">
      <button
        class="flex items-center px-3 py-2 border rounded text-white border-white hover:border-transparent hover:text-indigo-500 hover:bg-white"
        onclick="navBar()">
        Menu
      </button>
    </div>

    <div class="font-mono text-center block w-full flex-grow hidden lg:flex lg:items-center lg:w-auto" id="nav-items">
      <div class="text-sm lg:flex-grow">
      </div>
      {% if request.user.is_authenticated %}
      <div class="text-sm">
        <a class="block text-gray-200 rounded mt-4 lg:mt-0 mx-3 p-2 hover:bg-green-500 hover:border-green-500"
          href="{% url 'contacts:add' %}">
          Add
        </a>
      </div>
      <div class="text-sm">
        <a class="block text-gray-200 rounded mt-4 lg:mt-0 mx-3 p-2 hover:bg-purple-500"
          href="{% url 'contacts:favorites' %}">
          Favorites
        </a>
      </div>
      <div class="text-sm">
        <a class="block text-gray-200 rounded mt-4 lg:mt-0 mx-3 p-2 hover:bg-yellow-500"
          href="{% url 'contacts:filed' %}">
          Filed
        </a>
      </div>
      <div class="text-sm">
        <a class="block text-gray-200 rounded mt-4 lg:mt-0 mx-3 p-2 hover:bg-gray-500"
          href="{% url 'accounts:settings' %}">
          Settings
        </a>
      </div>
      <div class="text-sm">
        <a class="block text-gray-200 rounded mt-4 lg:mt-0 mx-3 p-2 hover:bg-red-500"
          href="{% url 'accounts:logout' %}">
          Sign out
        </a>
      </div>
      {% endif %}
    </div>
  </nav>

  <main class="min-h-screen pt-16 pb-40">
    {% block body_main %}
    {% endblock body_main %}
  </main>

  <footer class="absolute bottom-0 w-full bg-blue-900 text-white">
    {% block body_footer %}
    {% endblock body_footer %}

    <div class="flex items-center justify-between m-3 px-5 py-3">
      <div class="">
        <p class="text-gray-300 text-sm">
          Copyright &copy 2020
        </p>
        <p class="text-gray-400 text-sm">
          v0.1.0
        </p>
      </div>
      <div class="">
        <a href="https://github.com/Patrick564/contacts_calendar/" target="_blank">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="32" height="32">
            <path style="fill: #ffffff" fill-rule="evenodd"
              d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z">
            </path>
          </svg>
        </a>
      </div>
    </div>
  </footer>
</body>

</html>

contacts/templates/base/contact_pagination.html
{% if request.user.is_authenticated %}
<div class="flex justify-between border-b border-indigo-500 m-3 p-2 pb-4">
  {% if page_obj.has_previous %}
  <div class="">
    <a class="bg-transparent border-2 border-indigo-500 hover:bg-indigo-500 rounded m-3 px-4 py-2"
      href="?page={{ page_obj.previous_page_number }}">
      Previus
    </a>
  </div>
  {% else %}
  <div class="">
    <a class="bg-transparent border-2 border-indigo-500 hover:bg-indigo-500 rounded m-3 cursor-not-allowed px-4 py-2">
      Previus
    </a>
  </div>
  {% endif %}

  <div>
    <span>
      {{ page_obj.number }} - {{ page_obj.paginator.num_pages }}
    </span>
  </div>

  {% if page_obj.has_next %}
  <div class="">
    <a class="bg-transparent border-2 border-indigo-500 hover:bg-indigo-500 rounded m-3 px-4 py-2"
      href="?page={{ page_obj.next_page_number }}">
      Next
    </a>
  </div>
  {% else %}
  <div class="">
    <a class="bg-transparent border-2 border-indigo-500 hover:bg-indigo-500 rounded m-3 px-4 py-2 cursor-not-allowed">
      Next
    </a>
  </div>
  {% endif %}
</div>
{% endif %}

contacts/templates/base/contact_top_buttons.html
<div class="flex justify-between border-b border-gray-500 m-2 p-2">
  <div class="mx-2">
    <span># {{ contact.id }}</span>
  </div>
  <div class="static mx-2">
    <button onclick="optionButtons({{ contact.id }})">
      <img src="../../static/contact_list/img/dots.png" alt="options">
    </button>

    <div class="bg-white absolute border border-gray-800 rounded-md -ml-32 p-3 w-32 hidden" id="{{ contact.id }}">
      <a class="block font-mono bg-teal-200 border-double border-2 border-teal-400 hover:border-transparent hover:bg-teal-400 rounded my-3 px-2 py-1"
        href="{% url 'contacts:update' contact.id %}">
        Update
      </a>

      <form action="{% url 'contacts:add-favorite' contact.id %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="favorite" value="{% if contact.favorite %}False{% else %}True{% endif %}">
        <button
          class="block font-mono {% if contact.favorite %} bg-purple-400 {% endif %} border-2 border-purple-400 hover:border-transparent hover:bg-purple-400 rounded my-3 px-2 py-1"
          type="submit">
          Favorite
        </button>
      </form>

      <form action="{% url 'contacts:add-filed' contact.id %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="filed" value="{% if contact.filed %}False{% else %}True{% endif %}">
        <button
          class="block font-mono {% if contact.filed %} bg-yellow-400 {% endif %} border-2 border-double border-yellow-400 hover:border-transparent hover:bg-yellow-400 rounded my-3 px-2 py-1"
          type="submit">
          File
        </button>
      </form>

      <form action="{% url 'contacts:delete' contact.id %}" method="POST">
        {% csrf_token %}
        <button
          class="block font-mono bg-transparent border-2 border-dashed border-red-400 hover:border-transparent hover:bg-red-400 rounded my-3 px-2 py-1"
          type="submit">
          Delete
        </button>
      </form>
    </div>
  </div>
</div>